name: osx-x86_64

on:
  push:
    branches:
      - master
      - develop
      - 'feature/**'
      - 'release/**'
      - 'hotfix/**'
  pull_request:
    branches:
      - master
      - develop
      - 'feature/**'
      - 'release/**'
      - 'hotfix/**'

jobs:
  verify:
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install-graalvm
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: '21.0.0.2.java11'

      - name: install-native-image
        run: gu install native-image

      - name: cache-maven-repository
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: verify
        run: ./mvnw --batch-mode --update-snapshots clean verify

      - name: compress
        uses: svenstaro/upx-action@v2
        with:
          file: target/it/swt-native-plugin-it/target/native/osx-x86_64/swt-native-plugin-it
          args: --best
          strip: false

      - name: prepare-staging
        run: |
          mkdir staging
          cp -r target/swt-native-plugin-*.jar staging
          cp -r target/it/swt-native-plugin-it/target/native/osx-x86_64/swt-native-plugin-it staging
          cp -r target/it/swt-native-plugin-it/build.log staging

      - name: upload-package
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
